# 网站基本信息
title: 中国科大高能时域天文课题组
description: 中国科学技术大学高能时域天文研究组官方网站
baseurl: "" # 网站根路径
url: "https://你的用户名.github.io" # 网站完整URL

# Jekyll设置
theme: minima # 使用默认主题
plugins:
  - jekyll-feed # 支持RSS订阅

# 自定义变量
logo: "/assets/images/logo.png" # 网站logo路径

# 成员分类配置
member_categories:
  - 导师
  - 博士后
  - 博士
  - 硕士
  - 本科生
  - 毕业生

# 时间格式设置
timezone: Asia/Shanghai
date_format: "%Y年%m月%d日"

# 自定义CSS
minima:
  custom_css:
    - assets/css/custom.css # 自定义样式表